// Code generated by "enumer -type=OcodeKind -json -text"; DO NOT EDIT.

package ocode

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _OcodeKindName = "OpLNOpLSTROpDBOpDWOpDDOpAAAOpAADOpAAMOpAASOpADXOpALTEROpAMXOpCBWOpCDQOpCDQEOpCLCOpCLDOpCLIOpCLTSOpCMCOpCPUIDOpCQOOpCSOpCWDOpCWDEOpDAAOpDASOpDIVOpDSOpEMMSOpENTEROpESOpF2XM1OpFABSOpFADDPOpFCHSOpFCLEXOpFCOMOpFCOMPOpFCOMPPOpFCOSOpFDECSTPOpFDISIOpFDIVPOpFDIVRPOpFENIOpFINCSTPOpFINITOpFLD1OpFLDL2EOpFLDL2TOpFLDLG2OpFLDLN2OpFLDPIOpFLDZOpFMULPOpFNCLEXOpFNDISIOpFNENIOpFNINITOpFNOPOpFNSETPMOpFPATANOpFPREMOpFPREM1OpFPTANOpFRNDINTOpFRSTOROpFSOpFSCALEOpFSETPMOpFSINOpFSINCOSOpFSQRTOpFSUBPOpFSUBRPOpFTSTOpFUCOMOpFUCOMPOpFUCOMPPOpFXAMOpFXCHOpFXRSTOROpFXTRACTOpFYL2XOpFYL2XP1OpGETSECOpGSOpHLTOpICEBPOpIDIVOpIMULOpINTOOpINVDOpIRETOpIRETDOpIRETQOpJMPEOpLAHFOpLEAVEOpLFENCEOpLOADALLOpLOCKOpMFENCEOpMONITOROpMULOpMWAITOpNOPOpNTAKENOpPAUSEOpPOPAOpPOPADOpPOPFOpPOPFDOpPOPFQOpPUSHAOpPUSHADOpPUSHFOpPUSHFDOpPUSHFQOpRDMSROpRDPMCOpRDTSCOpRDTSCPOpREPOpREPEOpREPNEOpRETFOpRETNOpRSMOpSAHFOpSETALCOpSFENCEOpSSOpSTCOpSTDOpSTIOpSWAPGSOpSYSCALLOpSYSENTEROpSYSEXITOpSYSRETOpTAKENOpUD2OpVMCALLOpVMLAUNCHOpVMRESUMEOpVMXOFFOpWAITOpWBINVDOpWRMSROpXGETBVOpXRSTOROpXSETBV"

var _OcodeKindIndex = [...]uint16{0, 4, 10, 14, 18, 22, 27, 32, 37, 42, 47, 54, 59, 64, 69, 75, 80, 85, 90, 96, 101, 108, 113, 117, 122, 128, 133, 138, 143, 147, 153, 160, 164, 171, 177, 184, 190, 197, 203, 210, 218, 224, 233, 240, 247, 255, 261, 270, 277, 283, 291, 299, 307, 315, 322, 328, 335, 343, 351, 358, 366, 372, 381, 389, 396, 404, 411, 420, 428, 432, 440, 448, 454, 463, 470, 477, 485, 491, 498, 506, 515, 521, 527, 536, 545, 552, 561, 569, 573, 578, 585, 591, 597, 603, 609, 615, 622, 629, 635, 641, 648, 656, 665, 671, 679, 688, 693, 700, 705, 713, 720, 726, 733, 739, 746, 753, 760, 768, 775, 783, 791, 798, 805, 812, 820, 825, 831, 838, 844, 850, 855, 861, 869, 877, 881, 886, 891, 896, 904, 913, 923, 932, 940, 947, 952, 960, 970, 980, 988, 994, 1002, 1009, 1017, 1025, 1033}

const _OcodeKindLowerName = "oplnoplstropdbopdwopddopaaaopaadopaamopaasopadxopalteropamxopcbwopcdqopcdqeopclcopcldopcliopcltsopcmcopcpuidopcqoopcsopcwdopcwdeopdaaopdasopdivopdsopemmsopenteropesopf2xm1opfabsopfaddpopfchsopfclexopfcomopfcompopfcomppopfcosopfdecstpopfdisiopfdivpopfdivrpopfeniopfincstpopfinitopfld1opfldl2eopfldl2topfldlg2opfldln2opfldpiopfldzopfmulpopfnclexopfndisiopfneniopfninitopfnopopfnsetpmopfpatanopfpremopfprem1opfptanopfrndintopfrstoropfsopfscaleopfsetpmopfsinopfsincosopfsqrtopfsubpopfsubrpopftstopfucomopfucompopfucomppopfxamopfxchopfxrstoropfxtractopfyl2xopfyl2xp1opgetsecopgsophltopicebpopidivopimulopintoopinvdopiretopiretdopiretqopjmpeoplahfopleaveoplfenceoploadalloplockopmfenceopmonitoropmulopmwaitopnopopntakenoppauseoppopaoppopadoppopfoppopfdoppopfqoppushaoppushadoppushfoppushfdoppushfqoprdmsroprdpmcoprdtscoprdtscpoprepoprepeoprepneopretfopretnoprsmopsahfopsetalcopsfenceopssopstcopstdopstiopswapgsopsyscallopsysenteropsysexitopsysretoptakenopud2opvmcallopvmlaunchopvmresumeopvmxoffopwaitopwbinvdopwrmsropxgetbvopxrstoropxsetbv"

func (i OcodeKind) String() string {
	if i < 0 || i >= OcodeKind(len(_OcodeKindIndex)-1) {
		return fmt.Sprintf("OcodeKind(%d)", i)
	}
	return _OcodeKindName[_OcodeKindIndex[i]:_OcodeKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OcodeKindNoOp() {
	var x [1]struct{}
	_ = x[OpLN-(0)]
	_ = x[OpLSTR-(1)]
	_ = x[OpDB-(2)]
	_ = x[OpDW-(3)]
	_ = x[OpDD-(4)]
	_ = x[OpAAA-(5)]
	_ = x[OpAAD-(6)]
	_ = x[OpAAM-(7)]
	_ = x[OpAAS-(8)]
	_ = x[OpADX-(9)]
	_ = x[OpALTER-(10)]
	_ = x[OpAMX-(11)]
	_ = x[OpCBW-(12)]
	_ = x[OpCDQ-(13)]
	_ = x[OpCDQE-(14)]
	_ = x[OpCLC-(15)]
	_ = x[OpCLD-(16)]
	_ = x[OpCLI-(17)]
	_ = x[OpCLTS-(18)]
	_ = x[OpCMC-(19)]
	_ = x[OpCPUID-(20)]
	_ = x[OpCQO-(21)]
	_ = x[OpCS-(22)]
	_ = x[OpCWD-(23)]
	_ = x[OpCWDE-(24)]
	_ = x[OpDAA-(25)]
	_ = x[OpDAS-(26)]
	_ = x[OpDIV-(27)]
	_ = x[OpDS-(28)]
	_ = x[OpEMMS-(29)]
	_ = x[OpENTER-(30)]
	_ = x[OpES-(31)]
	_ = x[OpF2XM1-(32)]
	_ = x[OpFABS-(33)]
	_ = x[OpFADDP-(34)]
	_ = x[OpFCHS-(35)]
	_ = x[OpFCLEX-(36)]
	_ = x[OpFCOM-(37)]
	_ = x[OpFCOMP-(38)]
	_ = x[OpFCOMPP-(39)]
	_ = x[OpFCOS-(40)]
	_ = x[OpFDECSTP-(41)]
	_ = x[OpFDISI-(42)]
	_ = x[OpFDIVP-(43)]
	_ = x[OpFDIVRP-(44)]
	_ = x[OpFENI-(45)]
	_ = x[OpFINCSTP-(46)]
	_ = x[OpFINIT-(47)]
	_ = x[OpFLD1-(48)]
	_ = x[OpFLDL2E-(49)]
	_ = x[OpFLDL2T-(50)]
	_ = x[OpFLDLG2-(51)]
	_ = x[OpFLDLN2-(52)]
	_ = x[OpFLDPI-(53)]
	_ = x[OpFLDZ-(54)]
	_ = x[OpFMULP-(55)]
	_ = x[OpFNCLEX-(56)]
	_ = x[OpFNDISI-(57)]
	_ = x[OpFNENI-(58)]
	_ = x[OpFNINIT-(59)]
	_ = x[OpFNOP-(60)]
	_ = x[OpFNSETPM-(61)]
	_ = x[OpFPATAN-(62)]
	_ = x[OpFPREM-(63)]
	_ = x[OpFPREM1-(64)]
	_ = x[OpFPTAN-(65)]
	_ = x[OpFRNDINT-(66)]
	_ = x[OpFRSTOR-(67)]
	_ = x[OpFS-(68)]
	_ = x[OpFSCALE-(69)]
	_ = x[OpFSETPM-(70)]
	_ = x[OpFSIN-(71)]
	_ = x[OpFSINCOS-(72)]
	_ = x[OpFSQRT-(73)]
	_ = x[OpFSUBP-(74)]
	_ = x[OpFSUBRP-(75)]
	_ = x[OpFTST-(76)]
	_ = x[OpFUCOM-(77)]
	_ = x[OpFUCOMP-(78)]
	_ = x[OpFUCOMPP-(79)]
	_ = x[OpFXAM-(80)]
	_ = x[OpFXCH-(81)]
	_ = x[OpFXRSTOR-(82)]
	_ = x[OpFXTRACT-(83)]
	_ = x[OpFYL2X-(84)]
	_ = x[OpFYL2XP1-(85)]
	_ = x[OpGETSEC-(86)]
	_ = x[OpGS-(87)]
	_ = x[OpHLT-(88)]
	_ = x[OpICEBP-(89)]
	_ = x[OpIDIV-(90)]
	_ = x[OpIMUL-(91)]
	_ = x[OpINTO-(92)]
	_ = x[OpINVD-(93)]
	_ = x[OpIRET-(94)]
	_ = x[OpIRETD-(95)]
	_ = x[OpIRETQ-(96)]
	_ = x[OpJMPE-(97)]
	_ = x[OpLAHF-(98)]
	_ = x[OpLEAVE-(99)]
	_ = x[OpLFENCE-(100)]
	_ = x[OpLOADALL-(101)]
	_ = x[OpLOCK-(102)]
	_ = x[OpMFENCE-(103)]
	_ = x[OpMONITOR-(104)]
	_ = x[OpMUL-(105)]
	_ = x[OpMWAIT-(106)]
	_ = x[OpNOP-(107)]
	_ = x[OpNTAKEN-(108)]
	_ = x[OpPAUSE-(109)]
	_ = x[OpPOPA-(110)]
	_ = x[OpPOPAD-(111)]
	_ = x[OpPOPF-(112)]
	_ = x[OpPOPFD-(113)]
	_ = x[OpPOPFQ-(114)]
	_ = x[OpPUSHA-(115)]
	_ = x[OpPUSHAD-(116)]
	_ = x[OpPUSHF-(117)]
	_ = x[OpPUSHFD-(118)]
	_ = x[OpPUSHFQ-(119)]
	_ = x[OpRDMSR-(120)]
	_ = x[OpRDPMC-(121)]
	_ = x[OpRDTSC-(122)]
	_ = x[OpRDTSCP-(123)]
	_ = x[OpREP-(124)]
	_ = x[OpREPE-(125)]
	_ = x[OpREPNE-(126)]
	_ = x[OpRETF-(127)]
	_ = x[OpRETN-(128)]
	_ = x[OpRSM-(129)]
	_ = x[OpSAHF-(130)]
	_ = x[OpSETALC-(131)]
	_ = x[OpSFENCE-(132)]
	_ = x[OpSS-(133)]
	_ = x[OpSTC-(134)]
	_ = x[OpSTD-(135)]
	_ = x[OpSTI-(136)]
	_ = x[OpSWAPGS-(137)]
	_ = x[OpSYSCALL-(138)]
	_ = x[OpSYSENTER-(139)]
	_ = x[OpSYSEXIT-(140)]
	_ = x[OpSYSRET-(141)]
	_ = x[OpTAKEN-(142)]
	_ = x[OpUD2-(143)]
	_ = x[OpVMCALL-(144)]
	_ = x[OpVMLAUNCH-(145)]
	_ = x[OpVMRESUME-(146)]
	_ = x[OpVMXOFF-(147)]
	_ = x[OpWAIT-(148)]
	_ = x[OpWBINVD-(149)]
	_ = x[OpWRMSR-(150)]
	_ = x[OpXGETBV-(151)]
	_ = x[OpXRSTOR-(152)]
	_ = x[OpXSETBV-(153)]
}

var _OcodeKindValues = []OcodeKind{OpLN, OpLSTR, OpDB, OpDW, OpDD, OpAAA, OpAAD, OpAAM, OpAAS, OpADX, OpALTER, OpAMX, OpCBW, OpCDQ, OpCDQE, OpCLC, OpCLD, OpCLI, OpCLTS, OpCMC, OpCPUID, OpCQO, OpCS, OpCWD, OpCWDE, OpDAA, OpDAS, OpDIV, OpDS, OpEMMS, OpENTER, OpES, OpF2XM1, OpFABS, OpFADDP, OpFCHS, OpFCLEX, OpFCOM, OpFCOMP, OpFCOMPP, OpFCOS, OpFDECSTP, OpFDISI, OpFDIVP, OpFDIVRP, OpFENI, OpFINCSTP, OpFINIT, OpFLD1, OpFLDL2E, OpFLDL2T, OpFLDLG2, OpFLDLN2, OpFLDPI, OpFLDZ, OpFMULP, OpFNCLEX, OpFNDISI, OpFNENI, OpFNINIT, OpFNOP, OpFNSETPM, OpFPATAN, OpFPREM, OpFPREM1, OpFPTAN, OpFRNDINT, OpFRSTOR, OpFS, OpFSCALE, OpFSETPM, OpFSIN, OpFSINCOS, OpFSQRT, OpFSUBP, OpFSUBRP, OpFTST, OpFUCOM, OpFUCOMP, OpFUCOMPP, OpFXAM, OpFXCH, OpFXRSTOR, OpFXTRACT, OpFYL2X, OpFYL2XP1, OpGETSEC, OpGS, OpHLT, OpICEBP, OpIDIV, OpIMUL, OpINTO, OpINVD, OpIRET, OpIRETD, OpIRETQ, OpJMPE, OpLAHF, OpLEAVE, OpLFENCE, OpLOADALL, OpLOCK, OpMFENCE, OpMONITOR, OpMUL, OpMWAIT, OpNOP, OpNTAKEN, OpPAUSE, OpPOPA, OpPOPAD, OpPOPF, OpPOPFD, OpPOPFQ, OpPUSHA, OpPUSHAD, OpPUSHF, OpPUSHFD, OpPUSHFQ, OpRDMSR, OpRDPMC, OpRDTSC, OpRDTSCP, OpREP, OpREPE, OpREPNE, OpRETF, OpRETN, OpRSM, OpSAHF, OpSETALC, OpSFENCE, OpSS, OpSTC, OpSTD, OpSTI, OpSWAPGS, OpSYSCALL, OpSYSENTER, OpSYSEXIT, OpSYSRET, OpTAKEN, OpUD2, OpVMCALL, OpVMLAUNCH, OpVMRESUME, OpVMXOFF, OpWAIT, OpWBINVD, OpWRMSR, OpXGETBV, OpXRSTOR, OpXSETBV}

var _OcodeKindNameToValueMap = map[string]OcodeKind{
	_OcodeKindName[0:4]:            OpLN,
	_OcodeKindLowerName[0:4]:       OpLN,
	_OcodeKindName[4:10]:           OpLSTR,
	_OcodeKindLowerName[4:10]:      OpLSTR,
	_OcodeKindName[10:14]:          OpDB,
	_OcodeKindLowerName[10:14]:     OpDB,
	_OcodeKindName[14:18]:          OpDW,
	_OcodeKindLowerName[14:18]:     OpDW,
	_OcodeKindName[18:22]:          OpDD,
	_OcodeKindLowerName[18:22]:     OpDD,
	_OcodeKindName[22:27]:          OpAAA,
	_OcodeKindLowerName[22:27]:     OpAAA,
	_OcodeKindName[27:32]:          OpAAD,
	_OcodeKindLowerName[27:32]:     OpAAD,
	_OcodeKindName[32:37]:          OpAAM,
	_OcodeKindLowerName[32:37]:     OpAAM,
	_OcodeKindName[37:42]:          OpAAS,
	_OcodeKindLowerName[37:42]:     OpAAS,
	_OcodeKindName[42:47]:          OpADX,
	_OcodeKindLowerName[42:47]:     OpADX,
	_OcodeKindName[47:54]:          OpALTER,
	_OcodeKindLowerName[47:54]:     OpALTER,
	_OcodeKindName[54:59]:          OpAMX,
	_OcodeKindLowerName[54:59]:     OpAMX,
	_OcodeKindName[59:64]:          OpCBW,
	_OcodeKindLowerName[59:64]:     OpCBW,
	_OcodeKindName[64:69]:          OpCDQ,
	_OcodeKindLowerName[64:69]:     OpCDQ,
	_OcodeKindName[69:75]:          OpCDQE,
	_OcodeKindLowerName[69:75]:     OpCDQE,
	_OcodeKindName[75:80]:          OpCLC,
	_OcodeKindLowerName[75:80]:     OpCLC,
	_OcodeKindName[80:85]:          OpCLD,
	_OcodeKindLowerName[80:85]:     OpCLD,
	_OcodeKindName[85:90]:          OpCLI,
	_OcodeKindLowerName[85:90]:     OpCLI,
	_OcodeKindName[90:96]:          OpCLTS,
	_OcodeKindLowerName[90:96]:     OpCLTS,
	_OcodeKindName[96:101]:         OpCMC,
	_OcodeKindLowerName[96:101]:    OpCMC,
	_OcodeKindName[101:108]:        OpCPUID,
	_OcodeKindLowerName[101:108]:   OpCPUID,
	_OcodeKindName[108:113]:        OpCQO,
	_OcodeKindLowerName[108:113]:   OpCQO,
	_OcodeKindName[113:117]:        OpCS,
	_OcodeKindLowerName[113:117]:   OpCS,
	_OcodeKindName[117:122]:        OpCWD,
	_OcodeKindLowerName[117:122]:   OpCWD,
	_OcodeKindName[122:128]:        OpCWDE,
	_OcodeKindLowerName[122:128]:   OpCWDE,
	_OcodeKindName[128:133]:        OpDAA,
	_OcodeKindLowerName[128:133]:   OpDAA,
	_OcodeKindName[133:138]:        OpDAS,
	_OcodeKindLowerName[133:138]:   OpDAS,
	_OcodeKindName[138:143]:        OpDIV,
	_OcodeKindLowerName[138:143]:   OpDIV,
	_OcodeKindName[143:147]:        OpDS,
	_OcodeKindLowerName[143:147]:   OpDS,
	_OcodeKindName[147:153]:        OpEMMS,
	_OcodeKindLowerName[147:153]:   OpEMMS,
	_OcodeKindName[153:160]:        OpENTER,
	_OcodeKindLowerName[153:160]:   OpENTER,
	_OcodeKindName[160:164]:        OpES,
	_OcodeKindLowerName[160:164]:   OpES,
	_OcodeKindName[164:171]:        OpF2XM1,
	_OcodeKindLowerName[164:171]:   OpF2XM1,
	_OcodeKindName[171:177]:        OpFABS,
	_OcodeKindLowerName[171:177]:   OpFABS,
	_OcodeKindName[177:184]:        OpFADDP,
	_OcodeKindLowerName[177:184]:   OpFADDP,
	_OcodeKindName[184:190]:        OpFCHS,
	_OcodeKindLowerName[184:190]:   OpFCHS,
	_OcodeKindName[190:197]:        OpFCLEX,
	_OcodeKindLowerName[190:197]:   OpFCLEX,
	_OcodeKindName[197:203]:        OpFCOM,
	_OcodeKindLowerName[197:203]:   OpFCOM,
	_OcodeKindName[203:210]:        OpFCOMP,
	_OcodeKindLowerName[203:210]:   OpFCOMP,
	_OcodeKindName[210:218]:        OpFCOMPP,
	_OcodeKindLowerName[210:218]:   OpFCOMPP,
	_OcodeKindName[218:224]:        OpFCOS,
	_OcodeKindLowerName[218:224]:   OpFCOS,
	_OcodeKindName[224:233]:        OpFDECSTP,
	_OcodeKindLowerName[224:233]:   OpFDECSTP,
	_OcodeKindName[233:240]:        OpFDISI,
	_OcodeKindLowerName[233:240]:   OpFDISI,
	_OcodeKindName[240:247]:        OpFDIVP,
	_OcodeKindLowerName[240:247]:   OpFDIVP,
	_OcodeKindName[247:255]:        OpFDIVRP,
	_OcodeKindLowerName[247:255]:   OpFDIVRP,
	_OcodeKindName[255:261]:        OpFENI,
	_OcodeKindLowerName[255:261]:   OpFENI,
	_OcodeKindName[261:270]:        OpFINCSTP,
	_OcodeKindLowerName[261:270]:   OpFINCSTP,
	_OcodeKindName[270:277]:        OpFINIT,
	_OcodeKindLowerName[270:277]:   OpFINIT,
	_OcodeKindName[277:283]:        OpFLD1,
	_OcodeKindLowerName[277:283]:   OpFLD1,
	_OcodeKindName[283:291]:        OpFLDL2E,
	_OcodeKindLowerName[283:291]:   OpFLDL2E,
	_OcodeKindName[291:299]:        OpFLDL2T,
	_OcodeKindLowerName[291:299]:   OpFLDL2T,
	_OcodeKindName[299:307]:        OpFLDLG2,
	_OcodeKindLowerName[299:307]:   OpFLDLG2,
	_OcodeKindName[307:315]:        OpFLDLN2,
	_OcodeKindLowerName[307:315]:   OpFLDLN2,
	_OcodeKindName[315:322]:        OpFLDPI,
	_OcodeKindLowerName[315:322]:   OpFLDPI,
	_OcodeKindName[322:328]:        OpFLDZ,
	_OcodeKindLowerName[322:328]:   OpFLDZ,
	_OcodeKindName[328:335]:        OpFMULP,
	_OcodeKindLowerName[328:335]:   OpFMULP,
	_OcodeKindName[335:343]:        OpFNCLEX,
	_OcodeKindLowerName[335:343]:   OpFNCLEX,
	_OcodeKindName[343:351]:        OpFNDISI,
	_OcodeKindLowerName[343:351]:   OpFNDISI,
	_OcodeKindName[351:358]:        OpFNENI,
	_OcodeKindLowerName[351:358]:   OpFNENI,
	_OcodeKindName[358:366]:        OpFNINIT,
	_OcodeKindLowerName[358:366]:   OpFNINIT,
	_OcodeKindName[366:372]:        OpFNOP,
	_OcodeKindLowerName[366:372]:   OpFNOP,
	_OcodeKindName[372:381]:        OpFNSETPM,
	_OcodeKindLowerName[372:381]:   OpFNSETPM,
	_OcodeKindName[381:389]:        OpFPATAN,
	_OcodeKindLowerName[381:389]:   OpFPATAN,
	_OcodeKindName[389:396]:        OpFPREM,
	_OcodeKindLowerName[389:396]:   OpFPREM,
	_OcodeKindName[396:404]:        OpFPREM1,
	_OcodeKindLowerName[396:404]:   OpFPREM1,
	_OcodeKindName[404:411]:        OpFPTAN,
	_OcodeKindLowerName[404:411]:   OpFPTAN,
	_OcodeKindName[411:420]:        OpFRNDINT,
	_OcodeKindLowerName[411:420]:   OpFRNDINT,
	_OcodeKindName[420:428]:        OpFRSTOR,
	_OcodeKindLowerName[420:428]:   OpFRSTOR,
	_OcodeKindName[428:432]:        OpFS,
	_OcodeKindLowerName[428:432]:   OpFS,
	_OcodeKindName[432:440]:        OpFSCALE,
	_OcodeKindLowerName[432:440]:   OpFSCALE,
	_OcodeKindName[440:448]:        OpFSETPM,
	_OcodeKindLowerName[440:448]:   OpFSETPM,
	_OcodeKindName[448:454]:        OpFSIN,
	_OcodeKindLowerName[448:454]:   OpFSIN,
	_OcodeKindName[454:463]:        OpFSINCOS,
	_OcodeKindLowerName[454:463]:   OpFSINCOS,
	_OcodeKindName[463:470]:        OpFSQRT,
	_OcodeKindLowerName[463:470]:   OpFSQRT,
	_OcodeKindName[470:477]:        OpFSUBP,
	_OcodeKindLowerName[470:477]:   OpFSUBP,
	_OcodeKindName[477:485]:        OpFSUBRP,
	_OcodeKindLowerName[477:485]:   OpFSUBRP,
	_OcodeKindName[485:491]:        OpFTST,
	_OcodeKindLowerName[485:491]:   OpFTST,
	_OcodeKindName[491:498]:        OpFUCOM,
	_OcodeKindLowerName[491:498]:   OpFUCOM,
	_OcodeKindName[498:506]:        OpFUCOMP,
	_OcodeKindLowerName[498:506]:   OpFUCOMP,
	_OcodeKindName[506:515]:        OpFUCOMPP,
	_OcodeKindLowerName[506:515]:   OpFUCOMPP,
	_OcodeKindName[515:521]:        OpFXAM,
	_OcodeKindLowerName[515:521]:   OpFXAM,
	_OcodeKindName[521:527]:        OpFXCH,
	_OcodeKindLowerName[521:527]:   OpFXCH,
	_OcodeKindName[527:536]:        OpFXRSTOR,
	_OcodeKindLowerName[527:536]:   OpFXRSTOR,
	_OcodeKindName[536:545]:        OpFXTRACT,
	_OcodeKindLowerName[536:545]:   OpFXTRACT,
	_OcodeKindName[545:552]:        OpFYL2X,
	_OcodeKindLowerName[545:552]:   OpFYL2X,
	_OcodeKindName[552:561]:        OpFYL2XP1,
	_OcodeKindLowerName[552:561]:   OpFYL2XP1,
	_OcodeKindName[561:569]:        OpGETSEC,
	_OcodeKindLowerName[561:569]:   OpGETSEC,
	_OcodeKindName[569:573]:        OpGS,
	_OcodeKindLowerName[569:573]:   OpGS,
	_OcodeKindName[573:578]:        OpHLT,
	_OcodeKindLowerName[573:578]:   OpHLT,
	_OcodeKindName[578:585]:        OpICEBP,
	_OcodeKindLowerName[578:585]:   OpICEBP,
	_OcodeKindName[585:591]:        OpIDIV,
	_OcodeKindLowerName[585:591]:   OpIDIV,
	_OcodeKindName[591:597]:        OpIMUL,
	_OcodeKindLowerName[591:597]:   OpIMUL,
	_OcodeKindName[597:603]:        OpINTO,
	_OcodeKindLowerName[597:603]:   OpINTO,
	_OcodeKindName[603:609]:        OpINVD,
	_OcodeKindLowerName[603:609]:   OpINVD,
	_OcodeKindName[609:615]:        OpIRET,
	_OcodeKindLowerName[609:615]:   OpIRET,
	_OcodeKindName[615:622]:        OpIRETD,
	_OcodeKindLowerName[615:622]:   OpIRETD,
	_OcodeKindName[622:629]:        OpIRETQ,
	_OcodeKindLowerName[622:629]:   OpIRETQ,
	_OcodeKindName[629:635]:        OpJMPE,
	_OcodeKindLowerName[629:635]:   OpJMPE,
	_OcodeKindName[635:641]:        OpLAHF,
	_OcodeKindLowerName[635:641]:   OpLAHF,
	_OcodeKindName[641:648]:        OpLEAVE,
	_OcodeKindLowerName[641:648]:   OpLEAVE,
	_OcodeKindName[648:656]:        OpLFENCE,
	_OcodeKindLowerName[648:656]:   OpLFENCE,
	_OcodeKindName[656:665]:        OpLOADALL,
	_OcodeKindLowerName[656:665]:   OpLOADALL,
	_OcodeKindName[665:671]:        OpLOCK,
	_OcodeKindLowerName[665:671]:   OpLOCK,
	_OcodeKindName[671:679]:        OpMFENCE,
	_OcodeKindLowerName[671:679]:   OpMFENCE,
	_OcodeKindName[679:688]:        OpMONITOR,
	_OcodeKindLowerName[679:688]:   OpMONITOR,
	_OcodeKindName[688:693]:        OpMUL,
	_OcodeKindLowerName[688:693]:   OpMUL,
	_OcodeKindName[693:700]:        OpMWAIT,
	_OcodeKindLowerName[693:700]:   OpMWAIT,
	_OcodeKindName[700:705]:        OpNOP,
	_OcodeKindLowerName[700:705]:   OpNOP,
	_OcodeKindName[705:713]:        OpNTAKEN,
	_OcodeKindLowerName[705:713]:   OpNTAKEN,
	_OcodeKindName[713:720]:        OpPAUSE,
	_OcodeKindLowerName[713:720]:   OpPAUSE,
	_OcodeKindName[720:726]:        OpPOPA,
	_OcodeKindLowerName[720:726]:   OpPOPA,
	_OcodeKindName[726:733]:        OpPOPAD,
	_OcodeKindLowerName[726:733]:   OpPOPAD,
	_OcodeKindName[733:739]:        OpPOPF,
	_OcodeKindLowerName[733:739]:   OpPOPF,
	_OcodeKindName[739:746]:        OpPOPFD,
	_OcodeKindLowerName[739:746]:   OpPOPFD,
	_OcodeKindName[746:753]:        OpPOPFQ,
	_OcodeKindLowerName[746:753]:   OpPOPFQ,
	_OcodeKindName[753:760]:        OpPUSHA,
	_OcodeKindLowerName[753:760]:   OpPUSHA,
	_OcodeKindName[760:768]:        OpPUSHAD,
	_OcodeKindLowerName[760:768]:   OpPUSHAD,
	_OcodeKindName[768:775]:        OpPUSHF,
	_OcodeKindLowerName[768:775]:   OpPUSHF,
	_OcodeKindName[775:783]:        OpPUSHFD,
	_OcodeKindLowerName[775:783]:   OpPUSHFD,
	_OcodeKindName[783:791]:        OpPUSHFQ,
	_OcodeKindLowerName[783:791]:   OpPUSHFQ,
	_OcodeKindName[791:798]:        OpRDMSR,
	_OcodeKindLowerName[791:798]:   OpRDMSR,
	_OcodeKindName[798:805]:        OpRDPMC,
	_OcodeKindLowerName[798:805]:   OpRDPMC,
	_OcodeKindName[805:812]:        OpRDTSC,
	_OcodeKindLowerName[805:812]:   OpRDTSC,
	_OcodeKindName[812:820]:        OpRDTSCP,
	_OcodeKindLowerName[812:820]:   OpRDTSCP,
	_OcodeKindName[820:825]:        OpREP,
	_OcodeKindLowerName[820:825]:   OpREP,
	_OcodeKindName[825:831]:        OpREPE,
	_OcodeKindLowerName[825:831]:   OpREPE,
	_OcodeKindName[831:838]:        OpREPNE,
	_OcodeKindLowerName[831:838]:   OpREPNE,
	_OcodeKindName[838:844]:        OpRETF,
	_OcodeKindLowerName[838:844]:   OpRETF,
	_OcodeKindName[844:850]:        OpRETN,
	_OcodeKindLowerName[844:850]:   OpRETN,
	_OcodeKindName[850:855]:        OpRSM,
	_OcodeKindLowerName[850:855]:   OpRSM,
	_OcodeKindName[855:861]:        OpSAHF,
	_OcodeKindLowerName[855:861]:   OpSAHF,
	_OcodeKindName[861:869]:        OpSETALC,
	_OcodeKindLowerName[861:869]:   OpSETALC,
	_OcodeKindName[869:877]:        OpSFENCE,
	_OcodeKindLowerName[869:877]:   OpSFENCE,
	_OcodeKindName[877:881]:        OpSS,
	_OcodeKindLowerName[877:881]:   OpSS,
	_OcodeKindName[881:886]:        OpSTC,
	_OcodeKindLowerName[881:886]:   OpSTC,
	_OcodeKindName[886:891]:        OpSTD,
	_OcodeKindLowerName[886:891]:   OpSTD,
	_OcodeKindName[891:896]:        OpSTI,
	_OcodeKindLowerName[891:896]:   OpSTI,
	_OcodeKindName[896:904]:        OpSWAPGS,
	_OcodeKindLowerName[896:904]:   OpSWAPGS,
	_OcodeKindName[904:913]:        OpSYSCALL,
	_OcodeKindLowerName[904:913]:   OpSYSCALL,
	_OcodeKindName[913:923]:        OpSYSENTER,
	_OcodeKindLowerName[913:923]:   OpSYSENTER,
	_OcodeKindName[923:932]:        OpSYSEXIT,
	_OcodeKindLowerName[923:932]:   OpSYSEXIT,
	_OcodeKindName[932:940]:        OpSYSRET,
	_OcodeKindLowerName[932:940]:   OpSYSRET,
	_OcodeKindName[940:947]:        OpTAKEN,
	_OcodeKindLowerName[940:947]:   OpTAKEN,
	_OcodeKindName[947:952]:        OpUD2,
	_OcodeKindLowerName[947:952]:   OpUD2,
	_OcodeKindName[952:960]:        OpVMCALL,
	_OcodeKindLowerName[952:960]:   OpVMCALL,
	_OcodeKindName[960:970]:        OpVMLAUNCH,
	_OcodeKindLowerName[960:970]:   OpVMLAUNCH,
	_OcodeKindName[970:980]:        OpVMRESUME,
	_OcodeKindLowerName[970:980]:   OpVMRESUME,
	_OcodeKindName[980:988]:        OpVMXOFF,
	_OcodeKindLowerName[980:988]:   OpVMXOFF,
	_OcodeKindName[988:994]:        OpWAIT,
	_OcodeKindLowerName[988:994]:   OpWAIT,
	_OcodeKindName[994:1002]:       OpWBINVD,
	_OcodeKindLowerName[994:1002]:  OpWBINVD,
	_OcodeKindName[1002:1009]:      OpWRMSR,
	_OcodeKindLowerName[1002:1009]: OpWRMSR,
	_OcodeKindName[1009:1017]:      OpXGETBV,
	_OcodeKindLowerName[1009:1017]: OpXGETBV,
	_OcodeKindName[1017:1025]:      OpXRSTOR,
	_OcodeKindLowerName[1017:1025]: OpXRSTOR,
	_OcodeKindName[1025:1033]:      OpXSETBV,
	_OcodeKindLowerName[1025:1033]: OpXSETBV,
}

var _OcodeKindNames = []string{
	_OcodeKindName[0:4],
	_OcodeKindName[4:10],
	_OcodeKindName[10:14],
	_OcodeKindName[14:18],
	_OcodeKindName[18:22],
	_OcodeKindName[22:27],
	_OcodeKindName[27:32],
	_OcodeKindName[32:37],
	_OcodeKindName[37:42],
	_OcodeKindName[42:47],
	_OcodeKindName[47:54],
	_OcodeKindName[54:59],
	_OcodeKindName[59:64],
	_OcodeKindName[64:69],
	_OcodeKindName[69:75],
	_OcodeKindName[75:80],
	_OcodeKindName[80:85],
	_OcodeKindName[85:90],
	_OcodeKindName[90:96],
	_OcodeKindName[96:101],
	_OcodeKindName[101:108],
	_OcodeKindName[108:113],
	_OcodeKindName[113:117],
	_OcodeKindName[117:122],
	_OcodeKindName[122:128],
	_OcodeKindName[128:133],
	_OcodeKindName[133:138],
	_OcodeKindName[138:143],
	_OcodeKindName[143:147],
	_OcodeKindName[147:153],
	_OcodeKindName[153:160],
	_OcodeKindName[160:164],
	_OcodeKindName[164:171],
	_OcodeKindName[171:177],
	_OcodeKindName[177:184],
	_OcodeKindName[184:190],
	_OcodeKindName[190:197],
	_OcodeKindName[197:203],
	_OcodeKindName[203:210],
	_OcodeKindName[210:218],
	_OcodeKindName[218:224],
	_OcodeKindName[224:233],
	_OcodeKindName[233:240],
	_OcodeKindName[240:247],
	_OcodeKindName[247:255],
	_OcodeKindName[255:261],
	_OcodeKindName[261:270],
	_OcodeKindName[270:277],
	_OcodeKindName[277:283],
	_OcodeKindName[283:291],
	_OcodeKindName[291:299],
	_OcodeKindName[299:307],
	_OcodeKindName[307:315],
	_OcodeKindName[315:322],
	_OcodeKindName[322:328],
	_OcodeKindName[328:335],
	_OcodeKindName[335:343],
	_OcodeKindName[343:351],
	_OcodeKindName[351:358],
	_OcodeKindName[358:366],
	_OcodeKindName[366:372],
	_OcodeKindName[372:381],
	_OcodeKindName[381:389],
	_OcodeKindName[389:396],
	_OcodeKindName[396:404],
	_OcodeKindName[404:411],
	_OcodeKindName[411:420],
	_OcodeKindName[420:428],
	_OcodeKindName[428:432],
	_OcodeKindName[432:440],
	_OcodeKindName[440:448],
	_OcodeKindName[448:454],
	_OcodeKindName[454:463],
	_OcodeKindName[463:470],
	_OcodeKindName[470:477],
	_OcodeKindName[477:485],
	_OcodeKindName[485:491],
	_OcodeKindName[491:498],
	_OcodeKindName[498:506],
	_OcodeKindName[506:515],
	_OcodeKindName[515:521],
	_OcodeKindName[521:527],
	_OcodeKindName[527:536],
	_OcodeKindName[536:545],
	_OcodeKindName[545:552],
	_OcodeKindName[552:561],
	_OcodeKindName[561:569],
	_OcodeKindName[569:573],
	_OcodeKindName[573:578],
	_OcodeKindName[578:585],
	_OcodeKindName[585:591],
	_OcodeKindName[591:597],
	_OcodeKindName[597:603],
	_OcodeKindName[603:609],
	_OcodeKindName[609:615],
	_OcodeKindName[615:622],
	_OcodeKindName[622:629],
	_OcodeKindName[629:635],
	_OcodeKindName[635:641],
	_OcodeKindName[641:648],
	_OcodeKindName[648:656],
	_OcodeKindName[656:665],
	_OcodeKindName[665:671],
	_OcodeKindName[671:679],
	_OcodeKindName[679:688],
	_OcodeKindName[688:693],
	_OcodeKindName[693:700],
	_OcodeKindName[700:705],
	_OcodeKindName[705:713],
	_OcodeKindName[713:720],
	_OcodeKindName[720:726],
	_OcodeKindName[726:733],
	_OcodeKindName[733:739],
	_OcodeKindName[739:746],
	_OcodeKindName[746:753],
	_OcodeKindName[753:760],
	_OcodeKindName[760:768],
	_OcodeKindName[768:775],
	_OcodeKindName[775:783],
	_OcodeKindName[783:791],
	_OcodeKindName[791:798],
	_OcodeKindName[798:805],
	_OcodeKindName[805:812],
	_OcodeKindName[812:820],
	_OcodeKindName[820:825],
	_OcodeKindName[825:831],
	_OcodeKindName[831:838],
	_OcodeKindName[838:844],
	_OcodeKindName[844:850],
	_OcodeKindName[850:855],
	_OcodeKindName[855:861],
	_OcodeKindName[861:869],
	_OcodeKindName[869:877],
	_OcodeKindName[877:881],
	_OcodeKindName[881:886],
	_OcodeKindName[886:891],
	_OcodeKindName[891:896],
	_OcodeKindName[896:904],
	_OcodeKindName[904:913],
	_OcodeKindName[913:923],
	_OcodeKindName[923:932],
	_OcodeKindName[932:940],
	_OcodeKindName[940:947],
	_OcodeKindName[947:952],
	_OcodeKindName[952:960],
	_OcodeKindName[960:970],
	_OcodeKindName[970:980],
	_OcodeKindName[980:988],
	_OcodeKindName[988:994],
	_OcodeKindName[994:1002],
	_OcodeKindName[1002:1009],
	_OcodeKindName[1009:1017],
	_OcodeKindName[1017:1025],
	_OcodeKindName[1025:1033],
}

// OcodeKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OcodeKindString(s string) (OcodeKind, error) {
	if val, ok := _OcodeKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OcodeKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OcodeKind values", s)
}

// OcodeKindValues returns all values of the enum
func OcodeKindValues() []OcodeKind {
	return _OcodeKindValues
}

// OcodeKindStrings returns a slice of all String values of the enum
func OcodeKindStrings() []string {
	strs := make([]string, len(_OcodeKindNames))
	copy(strs, _OcodeKindNames)
	return strs
}

// IsAOcodeKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OcodeKind) IsAOcodeKind() bool {
	for _, v := range _OcodeKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for OcodeKind
func (i OcodeKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OcodeKind
func (i *OcodeKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OcodeKind should be a string, got %s", data)
	}

	var err error
	*i, err = OcodeKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for OcodeKind
func (i OcodeKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OcodeKind
func (i *OcodeKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = OcodeKindString(string(text))
	return err
}
